apiVersion: v1
data:
  AZURE_CLIENT_ID: {{ .Values.azureClientID | b64enc | quote }} 
  AZURE_CLIENT_SECRET: {{ .Values.azureClientSecret | b64enc | quote }}
  AZURE_TENANT_ID: {{ .Values.azureTenantID | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-az-sp-creds
